# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            I.AM.RYMNDHNG
tagline:          'Software Craftsman, Open Data & Vis'
description:      'Always another project away from something big.'
url:              http://www.rymndhng.com/blog

author:
  name:           'Ray H'
  url:            https://twitter.com/rymndhng

paginate:         5

# Custom vars
version:          1.0.0

github:
  url:            https://github.com/rymndhng

twitter:
  url:            https://twitter.com/rymndhng
