# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            rymndhng
tagline:          '(repeatedly #(do (coffee) (think) (write)))'
description:      'Personal Blog about Software Engineering and etc.'
url:              http://rymndhng.github.io

author:
  name:           'Raymond Huang'
  url:            https://twitter.com/rymndhng

paginate:         5

plugins:
  - jekyll-paginate

# Custom vars
version:          1.0.0

github:
  url:            https://github.com/rymndhng

twitter:
  url:            https://twitter.com/rymndhng
