# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            RYMDNHNG
tagline:          'Programming & Software Engineering'
description:      'Always another project and another tool to look at.'
url:              http://rymndhng.github.io

author:
  name:           'Ray H'
  url:            https://twitter.com/rymndhng

paginate:         5

# Custom vars
version:          1.0.0

github:
  url:            https://github.com/rymndhng

twitter:
  url:            https://twitter.com/rymndhng
